services:
  selenium-hub:
    image: selenium/hub:4.20.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-linux:
    image: selenium/node-chrome:4.20.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_CAPABILITIES=true
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_NODE_CAPABILITIES=[{"browserName":"chrome","platformName":"linux"}]

  firefox-linux:
    image: selenium/node-firefox:4.20.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_CAPABILITIES=true
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_NODE_CAPABILITIES=[{"browserName":"firefox","platformName":"linux"}]

  chrome-windows:
    image: selenium/node-chrome:4.20.0  # still Linux image, but logically tagged
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_CAPABILITIES=true
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_NODE_CAPABILITIES=[{"browserName":"chrome","platformName":"windows"}]
